pipeline {
    agent any
    
    parameters{
        // naming 
        string(defaultValue: "", description: "Deployment name", name: "deploymentName")
        // dropdown choices
        choice(choices: ["EU-WEST-2A", "EU-WEST-2B", "EU-WEST-2C"], description: "What AZ?", name: "azDeploy")
        // checkbox option
        booleanParam(defaultValue: "false", description: "CONFIRM DEPLOYMENT?", name: "confirmDeploy")
    }

    stages{
        stage("Demo"){
            steps{
                echo "String set to: ${deploymentName} \n"
                echo "Choice set to: ${azDeploy} \n"
                echo "Bool set to: ${confirmDeploy} \n"
            }
        }
    }
}